export const contactContent = {
  en: {
    title: "Contact Us",
    description:
      "We are here to help you plan your perfect trip. Reach out to us through any of the following platforms:",
    whatsapp: "WhatsApp",
    facebook: "Facebook",
    instagram: "Instagram",
    email: "Email",
    followUs: "Follow Us",
    addressTitle: "Our Address",
    address: "1234 Travel St, Colombo, Sri Lanka",
    phoneTitle: "Phone Number",
    phone: "+94 123 456 789",
    mapTitle: "Our Location",
    formTitle: "Send Us a Message",
    nameLabel: "Name",
    emailLabel: "Email",
    messageLabel: "Message",
    submitButton: "Submit",
  },
  he: {
    title: "צור קשר",
    description:
      "אנו כאן כדי לעזור לך לתכנן את הטיול המושלם. צור איתנו קשר באמצעות אחת מהפלטפורמות הבאות:",
    whatsapp: "וואטסאפ",
    facebook: "פייסבוק",
    instagram: "אינסטגרם",
    email: "אימייל",
    followUs: "עקוב אחרינו",
    addressTitle: "הכתובת שלנו",
    address: "רחוב הנסיעה 1234, קולומבו, סרי לנקה",
    phoneTitle: "מספר טלפון",
    phone: "+94 123 456 789",
    mapTitle: "המיקום שלנו",
    formTitle: "שלח לנו הודעה",
    nameLabel: "שם",
    emailLabel: "אימייל",
    messageLabel: "הודעה",
    submitButton: "שלח",
  },
};
