on:
  push:
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  build-and-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 🛠 Install dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{secrets.GIT_CPANEL_REACT_SERVER}}
          username: ${{ secrets.GIT_CPANEL_REACT_USER }}
          password: ${{ secrets.GIT_CPANEL_REACT_PASSWORD }}
          protocol: ${{ secrets.GIT_CPANEL_REACT_PROTOCOL }}
          local-dir: ./build/
